const express= require('express')
const { addProduct, searchProduct, findProduct, filterProduct, updateProduct, getProductById } = require('../Controllers/ProductController')
const router= express.Router()
const multer= require('multer')
const authenticateSeller = require('../Middleware/AuthMidlleware')
const storage= multer.memoryStorage()
const upload= multer({storage})

router.post('/addProduct',upload.single("image"),addProduct)
router.get('/findProducts',findProduct)
router.get('/searchProduct',authenticateSeller,searchProduct)
router.get('/filterProduct',authenticateSeller,filterProduct)
router.get('/getProductById/:id',authenticateSeller,getProductById)
router.put('/updateProduct/:id',upload.single("image"),updateProduct)
module.exports=router